### ISSUE TITLE
Target [Stancl\Tenancy\Contracts\StorageDriver] is not instantiable while building [Stancl\Tenancy\TenantManager]

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#297]
I have been getting this error for sometime now, and I have searched a lot and tried debugging but got nowhere.

```php
Target [Stancl\Tenancy\Contracts\StorageDriver] is not instantiable while building [Stancl\Tenancy\TenantManager]
```
I get this error while running `composer dump-autoload` or `php artisan package:discover`

**Comment by stancl** [comment]
Have you done `composer update`?

**Comment by tamkeen-tms** [comment]
Yes. Still getting the same error
```
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Stancl\Tenancy\Contracts\StorageDriver] is not instantiable while building [Stancl\Tenancy\TenantManager]. in vendor\laravel\framework\src\Illuminate\Container\Container.php:978
Stack trace:
#0 vendor\laravel\framework\src\Illuminate\Container\Container.php(812): Illuminate\Container\Container->notInstantiable('Stancl\\Tenancy\\...')
#1 vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('Stancl\\Tenancy\\...')
#2 vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->resolve('Stancl\\Tenancy\\...', Array)
#3 vendor\laravel\framework\src\Illuminate\Foundation\Application.php(776): Illuminate\Container\Container->make('Stancl\\Tenancy\\...', Array)
#4 vendor\laravel\framework\src\Illumin in vendor\laravel\framework\src\Illuminate\Container\Container.php on line 978
```

**Comment by stancl** [comment]
No one else reported this and this definitely doesn't happen with clean installs so I have no way of finding the cause of this.

**Comment by tamkeen-tms** [comment]
I am really sorry,

**Comment by tamkeen-tms** [comment]
Hello again.
I am really sorry, but I just cannot get passed this error, don't know what to do. Seconds ago, I upgraded to the latest release, in a fresh installation. And I still get the same error, it's driving me crazy!

```
[20-Apr-2020 11:07:11 UTC] PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Stancl\Tenancy\Contracts\StorageDriver] is not instantiable while building [Stancl\Tenancy\TenantManager]. in /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:978
Stack trace:
#0 /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): Illuminate\Container\Container->notInstantiable('Stancl\\Tenancy\\...')
#1 /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Stancl\\Tenancy\\...')
#2 /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('Stancl\\Tenancy\\...', Array, true)
#3 /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('Stancl\\Tenancy\\...', Array)
#4 /home/app/public_html/app/vendor/laravel/fra in /home/app/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 978
```

Here is my composer.json file
```json
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": ["framework", "laravel"],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=7.0.0",
    "barryvdh/laravel-elfinder": "^0.4.5",
    "doctrine/dbal": "2.9.x-dev",
    "facade/ignition": "1.16.1",
    "firebase/php-jwt": "dev-master",
    "giggsey/libphonenumber-for-php": "^8.0@dev",
    "intervention/image": "^2.3@dev",
    "laravel-notification-channels/twilio": "dev-master",
    "laravel/framework": "^6.0",
    "laravel/helpers": "^1.0@dev",
    "laravel/tinker": "^2.4",
    "laravelcollective/html": "^6.0@dev",
    "league/flysystem-ziparchive": "^1.0@dev",
    "league/omnipay": "^3.0@dev",
    "mikechip/chatapi": "dev-master",
    "moontoast/math": "dev-master",
    "omnipay/paypal": "^3.0@dev",
    "paragraph1/php-fcm": "dev-master",
    "pusher/pusher-php-server": "^3.4@dev",
    "ralouphie/mimey": "dev-master",
    "sentry/sentry-laravel": "^1.0@dev",
    "simplesoftwareio/simple-qrcode": "dev-master",
    "spatie/laravel-backup": "dev-master",
    "spatie/laravel-permission": "dev-master",
    "stancl/tenancy": "^2.3",
    "willvincent/feeds": "dev-master"
  },
  "require-dev": {
    "barryvdh/laravel-debugbar": "^3.3",
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~7.0",
    "symfony/css-selector": "3.1.*",
    "symfony/dom-crawler": "3.1.*"
  },
  "autoload": {
    "classmap": [
      "database"
    ],
    "psr-4": {
      "App\\": "app/"
    },
    "files":  ["app/Utils/Helpers.php"]
  },
  "minimum-stability": "stable",
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "scripts": {
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover"
    ],

    "post-root-package-install": [
      "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "php artisan key:generate"
    ],
    "post-install-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postInstall"
    ],
    "post-update-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postUpdate"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
  }
}
```

And here is my PHP -v output:
```
PHP 7.2.29 (cli) (built: Apr 14 2020 23:32:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.29, Copyright (c) 1999-2018, by Zend Technologies
```

Your help is very appreciated, I have been trying to fix this for so long.
Thanks in advance.

**Comment by stancl** [comment]
Show the package config, clear cache.

**Comment by tamkeen-tms** [comment]
Here the config/tenancy.php
```php
<?php

	declare(strict_types=1);

	return [
		'storage_driver' => 'db',
		'storage_drivers' => [
			'db' => [
				'driver' => Stancl\Tenancy\StorageDrivers\Database\DatabaseStorageDriver::class,
				'data_column' => 'data',
				'custom_columns' => [
					'name',
					//'plan',
					//'configuration',
				],
				'connection' => 'tenants', // Your central database connection. Set to null to use the default
				// connection.
				'table_names' => [
					'tenants' => 'tenants',
					'domains' => 'domains',
				],
			],
			'redis' => [
				'driver' => Stancl\Tenancy\StorageDrivers\RedisStorageDriver::class,
				'connection' => 'tenancy',
			],
		],
		'tenant_route_namespace' => 'App\Http\Controllers',
		'exempt_domains' => [ // e.g. domains which host landing pages, sign up pages, etc
			 env('TENANCY_CENTRAL_APP_DOMAIN'),
		],
		'database' => [
			'based_on' => 'tenant', // The connection that will be used as a base for the dynamically created tenant
			// connection. Set to null to use the default connection.
			'prefix' => 'tenant_',
			'suffix' => '',
		],
		'redis' => [
			'prefix_base' => 'tenant',
			'prefixed_connections' => [
				// 'default',
			],
		],
		'cache' => [
			'tag_base' => 'tenant',
		],
		'filesystem' => [ // https://tenancy.samuelstancl.me/docs/v2/filesystem-tenancy/
			'suffix_base' => 'tenants/',
			'suffix_storage_path' => true, // Note: Disabling this will likely break local disk tenancy. Only disable this if you're using an external file storage service like S3.
			// Disks which should be suffixed with the suffix_base + tenant id.
			'disks' => [
				'local',
				'public',
				// 's3',
			],
			'root_override' => [
				// Disks whose roots should be overriden after storage_path() is suffixed.
				'local' => '%storage_path%/app/',
				'public' => '%storage_path%/app/public/',
			],
		],
		'database_managers' => [
			// Tenant database managers handle the creation & deletion of tenant databases.
//			'sqlite' => Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager::class,
			'mysql' => Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager::class,
//			'pgsql' => Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager::class,
		],
		'database_manager_connections' => [
			// Connections used by TenantDatabaseManagers. This tells, for example, the
			// MySQLDatabaseManager to use the mysql connection to create databases.
//			'sqlite' => 'sqlite',
			'mysql' => 'tenant',
//			'pgsql' => 'pgsql',
		],
		'bootstrappers' => [
			// Tenancy bootstrappers are executed when tenancy is initialized.
			// Their responsibility is making Laravel features tenant-aware.
			'database' => Stancl\Tenancy\TenancyBootstrappers\DatabaseTenancyBootstrapper::class,
			'cache' => Stancl\Tenancy\TenancyBootstrappers\CacheTenancyBootstrapper::class,
			'filesystem' => Stancl\Tenancy\TenancyBootstrappers\FilesystemTenancyBootstrapper::class,
			'queue' => Stancl\Tenancy\TenancyBootstrappers\QueueTenancyBootstrapper::class,
			// 'redis' => Stancl\Tenancy\TenancyBootstrappers\RedisTenancyBootstrapper::class, // Note: phpredis is needed
		],
		'features' => [
			// Features are classes that provide additional functionality
			// not needed for tenancy to be bootstrapped. They are run
			// regardless of whether tenancy has been initialized.

			 Stancl\Tenancy\Features\Timestamps::class,
			 Stancl\Tenancy\Features\TenantConfig::class,
			// Stancl\Tenancy\Features\TelescopeTags::class,
//			 Stancl\Tenancy\Features\TenantRedirect::class,
		],
		'storage_to_config_map' => [ // Used by the TenantConfig feature
			// 'paypal_api_key' => 'services.paypal.api_key',
		],
		'home_url' => '/',
		'queue_database_creation' => env('TENANCY_QUEUE_TENANT_DB_CREATION'),
		'migrate_after_creation' => true, // run migrations after creating a tenant
		'migration_parameters' => [
			 '--force' => true, // force database migrations
		],
		'seed_after_migration' => true, // should the seeder run after automatic migration
		'seeder_parameters' => [
			'--class' => 'DatabaseSeeder', // root seeder class to run after automatic migrations, e.g.: 'DatabaseSeeder'
			 '--force' => true, // force database seeder
		],
		'queue_database_deletion' => true,
		'delete_database_after_tenant_deletion' => false, // delete the tenant's database after deleting the tenant
		'unique_id_generator' => \App\Tenant\MultiTenancy\TenantIdGenerator::class,
		'global_middleware' => [
			Stancl\Tenancy\Middleware\InitializeTenancy::class,
		],
	];
```

Trying to run any artisan * command gives the same error above, even config:clear or cache:clear.

**Comment by stancl** [comment]
Clear cache manually then (by deleting the files).

**Comment by tamkeen-tms** [comment]
Yes sure, did that. This is a fresh installation anyway, I just finished running `composer install`, then got the error above on the last step; the `package:discover` command that Laravel runs after composer:install.

**Comment by stancl** [comment]
Must be related to your software set up then. That's strange, works for everyone.

**Comment by tamkeen-tms** [comment]
Probably, but the error itself is coming directly from the library's code. I mean look at the stack trace, it's so short, the error is happening at the binding stage of the library.

**Comment by stancl** [comment]
It's not coming from the library's code. It's coming from the Container, saying it can't instantiate the library's class, which can be due to a ton of things.

**Comment by tamkeen-tms** [comment]
Care to suggest a couple? The most likely, and I can take it from there.

**Comment by stancl** [comment]
If there's an issue even with a completely fresh Laravel installation where you add nothing custom, then there's an issue with your PHP setup. Try running it in a docker container or something.

**Comment by watercayman** [comment]
I had this same issue when pulling in Tenancy in an existing project.  `php artisan *` all failed.

As Samuel noted above, manually clearing the cache files solved the issue.  Specifically, deleting `bootstrap\cache\packages.php` made the difference.

**Comment by tamkeen-tms** [comment]
For me, one or more config files had values that could not be evaluated duration the build, one config value was a closure for example. After fixing these issue the problem disappeared.
