### ISSUE TITLE
Catch TenantCouldNotBeIdentifiedOnDomainException globally?

### ISSUE THREAD

**Issue by renege** [archtechx/tenancy#677]
Hi,
I'm getting 500 errors, when people use a non-working domain.
```
[message]
Tenant could not be identified on domain www {"exception":"[object] (Stancl\\Tenancy\\Exceptions\\TenantCouldNotBeIdentifiedOnDomainException(code: 0): Tenant could not be identified on domain www at /app/vendor/stancl/tenancy/src/Resolvers/DomainTenantResolver.php:48)
[stacktrace]
#0 /app/vendor/stancl/tenancy/src/Resolvers/Contracts/CachedTenantResolver.php(34): Stancl\\Tenancy\\Resolvers\\DomainTenantResolver->resolveWithoutCache('www')
#1 /app/vendor/stancl/tenancy/src/Middleware/IdentificationMiddleware.php(26): Stancl\\Tenancy\\Resolvers\\Contracts\\CachedTenantResolver->resolve('www')
#2 /app/vendor/stancl/tenancy/src/Middleware/InitializeTenancyBySubdomain.php(52): Stancl\\Tenancy\\Middleware\\IdentificationMiddleware->initializeTenancy(Object(Illuminate\\Http\\Request), Object(Closure), 'www')
#3 /app/vendor/stancl/tenancy/src/Middleware/InitializeTenancyByDomainOrSubdomain.php(22): Stancl\\Tenancy\\Middleware\\InitializeTenancyBySubdomain->handle(Object(Illuminate\\Http\\Request), Object(Closure))
```

Is there a way to Catch the specific `TenantCouldNotBeIdentifiedOnDomainException` and forward users to a specific page it that error occurs?

**Comment by stancl** [comment]
Please respect the issue templates.

**Comment by donmbelembe** [comment]
@renege  did you find the solution ?

**Comment by sarmenb** [comment]
#### Solution that works like a charm!!

go to Providers/TenancyServiceProvider and in the boot method put this

```
InitializeTenancyByDomain::$onFail = function ($exception, $request, $next) {
            return redirect(config('app.url')); //can be a custom url it redirects to or you can show a custom error page
        };
```

**Comment by Sharifur** [comment]
@sarmenb thanks man.

solved my issue

**Comment by donmbelembe** [comment]
@sarmenb doesn't work for me
