### ISSUE TITLE
Laravel 8 - Batchable Jobs

### ISSUE THREAD

**Issue by soundar8562** [archtechx/tenancy#696]
Thank you for your great package 
Is there any option for Laravel 8 jobs batching on this package? If not could it be great to add?
FYI: https://laravel.com/docs/8.x/queues#dispatching-batches

#### Why this should be added
Laravel's job batching feature allows you to easily execute a batch of jobs and then perform some action when the batch of jobs has completed executing.

**Comment by stancl** [comment]
Yeah, in v4 I'd like to have first-class support for job batches.

I think you can use JobPipelines as an alternative right now. See https://github.com/archtechx/jobpipeline

**Comment by soundar8562** [comment]
Thanks for your reply, when we can expect **v4**?

**Comment by samtlewis** [comment]
@soundar8562 @stancl 
Not sure if I'm missing something but Batch jobs seem to work just fine to me. I've got a few different batch jobs setup and haven't seen any issues so far. Are there gotchas I should be looking for?

**Comment by stancl** [comment]
I think some other people reported issues in our Discord, but going to close this now and reopen if we get more feedback here.

**Comment by sebestenyb** [comment]
I tried using batchable jobs with this package, but if I dispatch the job from a tenant context, I end up with the following error:

```
[2025-07-09 02:40:59] local.ERROR: Call to a member function prepare() on null {"exception":"[object] (Error(code: 0): Call to a member function prepare() on null at /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Connection.php:423)
[stacktrace]
#0 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#1 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#2 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#3 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2913): Illuminate\\Database\\Connection->select('select * from `...', Array, false)
#4 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2902): Illuminate\\Database\\Query\\Builder->runSelect()
#5 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3456): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#6 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2901): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#7 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(333): Illuminate\\Database\\Query\\Builder->get(Array)
#8 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php(82): Illuminate\\Database\\Query\\Builder->first()
#9 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Bus/Batchable.php(38): Illuminate\\Bus\\DatabaseBatchRepository->find('9f5899b4-d51c-4...')
#10 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(278): App\\Jobs\\InternalApi\\Bookings\\RescheduleBooking->batch()
#11 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(256): Illuminate\\Queue\\CallQueuedHandler->ensureFailedBatchJobIsRecorded('2fad6926-d0b2-4...', Object(App\\Jobs\\InternalApi\\Bookings\\RescheduleBooking), Object(Error))
#12 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(236): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(Error), '2fad6926-d0b2-4...')
#13 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(215): Illuminate\\Queue\\Jobs\\Job->failed(Object(Error))
#14 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(596): Illuminate\\Queue\\Jobs\\Job->fail(Object(Error))
#15 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(542): Illuminate\\Queue\\Worker->failJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Error))
#16 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(465): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 3, Object(Error))
#17 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(443): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(Error))
#18 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#19 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#20 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon('redis', 'localco-default', Object(Illuminate\\Queue\\WorkerOptions))
#21 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'localco-default')
#22 /Users/[retracted]/Sites/[retracted]/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#24 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#29 /Users/[retracted]/Sites/[retracted]/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /Users/[retracted]/Sites/[retracted]/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/[retracted]/Sites/[retracted]/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /Users/[retracted]/Sites/[retracted]/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /Users/[retracted]/Sites/[retracted]/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /Users/[retracted]/Sites/[retracted]/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 {main}
"} 
```

Super simple example:

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Batchable;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestBatchJob implements ShouldQueue
{
    use Batchable;
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function handle(): void
    {
        //
    }
}
```

```php
<?php

namespace App\Console\Commands;

use App\Jobs\TestBatchJob;
use Illuminate\Bus\Batch;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Log;
use Stancl\Tenancy\Concerns\HasATenantsOption;
use Stancl\Tenancy\Concerns\TenantAwareCommand;
use Throwable;

class TestBatchJobCommand extends Command
{
    // Un-commenting these lines will result the error above 
    //    use HasATenantsOption;
    //    use TenantAwareCommand;

    /**
     * @var string
     */
    protected $signature = 'app:test-batch-job-command';

    /**
     * @var string
     */
    protected $description = 'Command description';

    /**
     * @throws Throwable
     */
    public function handle(): int
    {
        Bus::batch([
            new TestBatchJob(),
            new TestBatchJob(),
            new TestBatchJob(),
        ])
            ->before(fn (Batch $batch) => Log::debug('The batch has been created but no jobs have been added'))
            ->progress(fn (Batch $batch) => Log::debug('A single job has completed successfully'))
            ->catch(fn (Batch $batch) => Log::error('First batch job failure detected.'))
            ->finally(fn (Batch $batch) => Log::debug('The batch has finished executing.'))
            ->dispatch();

        return 0;
    }
}

```

PS: The app is on Laravel `v10.48.29` and Laravel Tenancy `v3.9.1`

**Comment by sebestenyb** [comment]
Looks like I missed a section from our queue config, adding it fixed the issue:

```php
    'batching' => [
        'database' => env('DB_CONNECTION', 'sqlite'),
        'table' => 'job_batches',
    ],
```
